# .readthedocs.yml

# Required
version: 2

build:
  image: latest

python:
   version: '3.8'
   install:
      - requirements: docs/requirements.txt
      - method: pip
        path: src
      #   extra_requirements:
      #       - docs
      # - method: setuptools
      #   path: src
   system_packages: true

formats:
  - epub
  # - pdf

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false